### ISSUE TITLE
Long file names do not work well in the nav bar

### ISSUE THREAD

**Issue by Shehan29** [FYDP-SAAC/yada#64]
Probably need to just show the first `n` characters in order to ensure that spacing works correctly

**Comment by ca-shen98** [comment]
@aravind-segu @Shehan29 is the full file name every readable then? Shouldn't the card be expanded vertically and the text wrapped instead of only showing the first n characters. When the list used <button> tags, this was done using css with some word-wrap or white-space or both css property.
