### ISSUE TITLE
Make Navbar and Tag Pane Stick to the top of the screen

### ISSUE THREAD

**Issue by aravind-segu** [FYDP-SAAC/yada#66]
![image](https://user-images.githubusercontent.com/23442083/106969792-906f7900-6719-11eb-9e75-633dbbe42888.png)
On Scroll it seems weird to scroll up to add tags and save the doc. Try to make the nav bar and tag pane stick.

**Comment by ca-shen98** [comment]
Previously, this wasn't an issue (for view heights > like 240px or something) because the app height was adjusted to only fit within the screen. Something must've been changed with how the css is handling this.
