### ISSUE TITLE
File get corrupted if user leaves source after saving

### ISSUE THREAD

**Issue by AkshayPall** [FYDP-SAAC/yada#80]
1. Modify a doc
2. Press Save
3. Immediately jump to another doc before you see the `source saved` toast
4. Once the toast is seen, return to the source document

<img width="1280" alt="Screen Shot 2021-02-05 at 8 22 57 AM" src="https://user-images.githubusercontent.com/10256087/107039082-6c4c8000-678b-11eb-89b6-17c184a2b39c.png">

**Comment by ca-shen98** [comment]
I'll try to refactor the saving code, and hopefully should fix this, although I currently can't repro the bug
